### ISSUE TITLE
Ports (in Concepts)

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#10]
In Definition, I changed the first sentence of the 2nd para to read

> Flow-based programming considers an application as a set of processes ("black boxes") communicating via connections, which the processes access by means of "ports".

Assuming there are no objections to this, I would like to add a "Connections" heading to Concepts, before Ports, and then use the same phrasing in Connections.

The only problem is I'm not sure how we should describe connections to embrace _both_ FBP and NoFlo.  So I'll tag this as a question.  Could someone take a stab at this?!

BTW In FBP, connections correspond 1:1 to (non-IIP) input ports or input array port elements.  Say this somewhere?

**Comment by bergie** [comment]
@jpaulm I think the main difference between NoFlo and classical FBP is that the _current_ NoFlo connection implementation is 0-capacity, i.e. packet that is sent through the connection immediately goes to the inport, though inports themselves are capable of doing buffering.

As long as there is a concept of defined connection capacities, NoFlo would therefore fit without problems. And we can easily do other types of connections than just the current (`EventEmitter`-based) one.

Right now I'm for example doing some network-to-network connections via AMQP. Something we may bring into NoFlo proper at some point.

**Comment by jpaulm** [comment]
I have added the Connections sub-head, and have put some words under it, and in Ports and Input Ports.  I am still confused about issue #8, so I haven't changed that sentence.  Perhaps someone could look at these sections of Concepts, and make whatever changes they see fit...

**Comment by jpaulm** [comment]
I think we can close this one too...
