### ISSUE TITLE
Terminology - loopers/non-loopers

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#11]
Don't see connection between the looper/non-looper concept and the resident/non-resident dichotomy!  Perhaps someone could explain..?

**Comment by oleksandr** [comment]
As far as I understand a resident process has a system process or a green thread constantly running (once created and is not destroyed until the network is shutdown) - it resides in memory (heap?) and consuming CPU cycles. Typical looper in the classical FBP terms, right? Non-resident is rather a function called by runtime, processed the IP, sent to output port and deallocated resources (memory, CPU cycles).

**Comment by jpaulm** [comment]
That's interesting!  You're right, that is pretty close! However it sounds like resident and non-resident are more different than loopers vs. non-loopers - the latter distinction arises simply from the FBP activation rules. Since a component which decides to return to the scheduler will be reactivated if more data arrives, or is waiting, at an input port, a non-looper is simply a component which returns to its caller (the scheduler) more often.  When it does this, any local data is lost.  This means, for instance, that you could have a "partial" non-looper, where, say, the component returns after every close bracket, or after every 5th IP.  

So a "total" non-looper is much like a conventional subroutine, so can share a stack with other non-loopers.  This makes them appealing in a number of ways.

**Comment by oleksandr** [comment]
I agree. It seems like we're facing the same issue of how the model maps into specific implementation. In some runtimes based on "green threads", where the scheduler has more responsibilities (once we've touched this topic - recalling "pulling the blanket"), it makes total sense and it is a straight-forward implementation. In other cases especially with system processes it makes sense to start network's processes at once and keep them active (which means either idling and listening for inputs or processing the IPs) because spawning a system level process is an expensive operation. 
Additionally it could be difficult to implement with certain communication middleware in distributed runtime implementation, where the scheduler has less responsibilities: network processes are interconnected and scheduler is not aware about every IP passing the connections.

I think this is why Victor used terms resident/non-resident instead of loopers/non-loopers: sometimes it's cheaper to keep the green thread or system thread/process running...

**Comment by alfa256** [comment]
@jpaulm  Take a look at my edits, I think that it should be more of a component design consideration rather than a requirement. I gave a little example to help with the idea. It would be nice if you could add another example.

**Comment by jpaulm** [comment]
@alfa256 I have made a small change to Loopers - could you take a look?   At least from my point of view your change to Non-loopers was fine.

@oleksandr  do you want to add some words?  I can't speak for other possible implementations, so perhaps you could say if you think more has to be added...

BTW In FBP, processes with non-IIP input ports start when the first data IP arrives - there are some situations where this helpful, although I agree it is probably not an essential feature.

**Comment by oleksandr** [comment]
@jpaulm sure. I just want to clarify this point and agree on it. Here's another example from the implementation side: 
- each process is a system process
- bounded connections are established between the processes (beyond scheduler; well, scheduler pass all required interconnection data upon system process launch)
- scheduler is responsible for loading graph, parsing, validating, resolving components (code location), creating system processes, monitoring processes as much as it's possible (state={running, exit}, access to stdin/stdout/stderr and that's pretty much it)
- scheduler is rather a system process manager once the network is running

In this kind of implementation it's hard to say that a process starts when the first data IP arrives. In fact the processes are already started (as executables) and system resources are allocated (they consume memory and CPU, even if at minimum when idling). They are listening for the input ports. From this point of view I would say that process can be in the idle state (not processing IPs) and in active state (processing IPs). It's really hard to map classical FBP lifecycle here.

What do you think?

**Comment by bergie** [comment]
@oleksandr there are many ways to do this... each process could be a system process. It could be a thread. Or maybe it can even be its own machine. So I wouldn't lock it down to _each process is a system process_

**Comment by oleksandr** [comment]
@bergie of course. I've just provided an example of how it can be difficult to map theory to the implementation. The outcome I expect from this discussion is to move loopers/non-loopers and the classical life-cycle to the optional section...

**Comment by bergie** [comment]
I think life-cycle is interesting. Currently NoFlo's single-threaded model doesn't need it, but for stuff like having a Heroku worker per process it would actually save a lot of money to have a smart way to start/stop workers as the graph execution progresses.

**Comment by jpaulm** [comment]
@oleksandr @bergie You both make good points!  However, now I'm confused - is this wiki trying to find the common base-line for anything that might be described as FBP-like?  Or is is just for "classical" FBP?  If the latter, then I assume you are OK with the present definitions for loopers and non-loopers;  if the former, I agree that they may not even apply.  Also, "classical" FBP doesn't really "listen" on input ports, which to me implies that _something_ has to be running to do the listening...

This is why BTW I thought it important to describe the scheduler logic in my book - once you have internalized it, it becomes easy to reason about an FBP application, because you don't have to worry about the sequence in which events occur - except as defined by the two laws described in the book.

**Comment by trustmaster** [comment]
Let me remind it: we want Definition page to be absolutely vital for all FBP systems, Concepts to be common among most of them and Advanced features to represent some advanced things which may be implementation-specific.

**Comment by jpaulm** [comment]
Hi @trustmaster  , I'm afraid there is a danger of circularity here!  Does the Definition page _pre_scribe what is FBP, or does it _de_scribe one or more implementations of FBP?  If we are going to include NoFlo and other "reactive" FBP-like systems in this wiki, IMO we are going to have a very hard time finding wording that embraces both "reactive" and "classical" FBP...  

Alternatively we could come up with a (short) list of the essential characteristics of FBP.  I actually tried to do that some years ago, proposing a tripod (on the basis that a tripod is more stable than a chair with 4 legs!):
- asynchronous processes 
- connections defined externally to processes
- communication by means of streams of data chunks, each with a definite lifetime

I think that even covers the situation where every process is on a separate device!

**Comment by oleksandr** [comment]
@jpaulm :+1: for the tripod definition. It's not that restricting. And yes I thought the wiki should define the baseline for FBP and the more specific stuff can be described in the "specifics" of the implementations.

**Comment by jpaulm** [comment]
@trustmaster based on @oleksandr 's comment, should we try some restructuring?  What do you think?

**Comment by trustmaster** [comment]
I'm closing this issue for now because [this post](https://github.com/flowbased/flowbased.org/issues/11#issuecomment-47024871) gives a sufficient description of the difference between loopers/non-loopers and resident/non-resident processes. Loopers/non-loopers remain to be generic FBP terms, while resident/non-resident is implementation details.
