### ISSUE TITLE
Terminology - Process

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#12]
> Each component may spawn one or several processes

In FBP, a component is viewed as passive - it can't _do_ anything! So assuming that you mean that each node is a single process, which executes component code, it is not really  recommended that one process spawn other processes - unless this is hidden from the network. The discussion of self-modifying networks is a separate issue, and has not really been implemented extensively in FBP.

**Comment by bergie** [comment]
I guess the correct way to say it would be something like:

> Each component can be used to spawn one or several processes

**Comment by jpaulm** [comment]
Hi @bergie , that's better, but strangely I still didn't get it immediately! How about something like,

"Nodes in the graph represent asynchronously executing processes, which execute code components or subgraphs.  The same component may be executed by more than one process concurrently." 

Did I grasp what you meant correctly?

**Comment by trustmaster** [comment]
@jpaulm that's quite complicated. I'd prefer one sentence similar to what @bergie suggested.

**Comment by jpaulm** [comment]
@trustmaster  I agree!  But @bergie 's statement seems backwards!  Processes for me are primary, and the component code is just its set of instructions.  Oddly enough, in the old days, this was the hardest concept to convey to old-school programmers!

How about something like:

"Processes are the units of concurrency in an FBP network, with their own local storage and resources.  Multiple processes can share the same component code, which should be read-only."

**Comment by bergie** [comment]
Maybe the more familiar OOP terminology here? _Multiple processes can be instantiated from the same component code_

**Comment by jpaulm** [comment]
hanks @bergie , that's definitely closer, but remember that the process is primary, and has its own attributes - only one of which is the component code.  The OOP phrasing sort of _suggests_ that the multiple processes running the same code are identical - I may be wrong...?

I still like mine better, but maybe we don't need the phrase " with their own local storage and resources."

**Comment by jpaulm** [comment]
I have just rephrased the second sentence.  I found myself trying to explain everything all over again - so I have just put a minimal definition there!  Please take a look.

**Comment by jpaulm** [comment]
Sorry!  Didn't mean to close it!

**Comment by oleksandr** [comment]
@jpaulm :+1: The current definition is fine with me. Any other objections?

**Comment by jpaulm** [comment]
Great!  If we don't get any more suggestions in the next little while, we can close this issue...?,

**Comment by jpaulm** [comment]
Sounds like that's a wrap!  Closing this issue...
