### ISSUE TITLE
Output Backwards

### ISSUE THREAD

**Issue by alfa256** [flowbased/flow-based.org#16]
A description is needed for this concept.

**Comment by jpaulm** [comment]
Hi @alfa256 where should this description go - this is really a design approach, similar to top-down and bottom-up in conventional programming.

**Comment by alfa256** [comment]
It's listed on Advanced Features but I would move it to a "Design" chapter,
What do you think?

2014-08-02 14:47 GMT-03:00 jpaulm notifications@github.com:

> Hi @alfa256 https://github.com/alfa256 where should this description go
> - this is really a design approach, similar to top-down and bottom-up in
>   conventional programming.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/flowbased/flowbased.org/issues/16#issuecomment-50969500
> .

## 

_Phanta Rei._
My FBP Blog: FlowBased http://flowbased.tk

**Comment by jpaulm** [comment]
Sounds good to me!  Will you add a "Design" chapter, and maybe 'salt' it
with some well-chosen words...?

Thanks,

Paul

**Comment by alfa256** [comment]
Already added it, edit the page whenever you feel like it.

2014-08-02 14:52 GMT-03:00 jpaulm notifications@github.com:

> Sounds good to me! Will you add a "Design" chapter, and maybe 'salt' it
> with some well-chosen words...?
> 
> Thanks,
> 
> Paul
> 
> On Sat, Aug 2, 2014 at 1:49 PM, alfa256 notifications@github.com wrote:
> 
> > It's listed on Advanced Features but I would move it to a "Design"
> > chapter,
> > What do you think?
> > 
> > 2014-08-02 14:47 GMT-03:00 jpaulm notifications@github.com:
> > 
> > > Hi @alfa256 https://github.com/alfa256 where should this
> > > description
> > > go
> > > - this is really a design approach, similar to top-down and bottom-up
> > >   in
> > >   conventional programming.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/flowbased/flowbased.org/issues/16#issuecomment-50969500>
> > 
> > > .
> > 
> > ## 
> > 
> > _Phanta Rei._
> > My FBP Blog: FlowBased http://flowbased.tk
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/flowbased/flowbased.org/issues/16#issuecomment-50969568>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/flowbased/flowbased.org/issues/16#issuecomment-50969641
> .

## 

_Phanta Rei._
My FBP Blog: FlowBased http://flowbased.tk
