### ISSUE TITLE
Advanced Features/Feedback Loops

### ISSUE THREAD

**Issue by alfa256** [flowbased/flow-based.org#17]
Explanation required.

**Comment by jpaulm** [comment]
There is no heading for this - should it be under Flow Features?   By the way, are you asking about loop topologies in networks?  If so, I can give it a try.

**Comment by alfa256** [comment]
It's in https://github.com/flowbased/flowbased.org/wiki/Concepts too, so it's up to you., I didn't add that item to the file but @trustmaster .

**Comment by jpaulm** [comment]
Hi Vladimir,

What did you have in mind?

Cheers,

Paul

**Comment by trustmaster** [comment]
Right, I meant "Loop type networks" in terms of the book and components with outputs looped back to inputs. I thought this is important since most dataflow systems don't allow it, while FBP uses them to implement interesting stuff like iterative algos, recursive algos and responsive UIs.

**Comment by jpaulm** [comment]
OK, got it! I'll try to come up with something over the next few days. Not
sure about recursive though - I raised that as an issue already!

Regards,

Paul

**Comment by bergie** [comment]
Loop-type networks are quite common when building interactive applications (see the [Flux pattern from Facebook](http://facebook.github.io/react/docs/flux-overview.html)) as well as with when reading a hierarchical file system.

[Here](http://app.flowhub.io/#example/1d42f66f5cc4614df935) is one example:

![screenshot 2014-08-14 at 13 13 10](https://cloud.githubusercontent.com/assets/3346/3919165/05d9e0ba-23a4-11e4-8737-c65f4c65f529.png)

**Comment by jpaulm** [comment]
Hi Henri,

You're right - I was quoting someone else.  I'll change or drop that
statement!

Thanks,

Paul

**Comment by jpaulm** [comment]
I think we can close this one as nobody seems to have changed the section on Feedback loops recently...?

**Comment by trustmaster** [comment]
@jpaulm just being lazy or busy. Feel free to update the section and close this issue then.

**Comment by jpaulm** [comment]
Looks like the section on Feedback loops is fairly stable... (?)
