### ISSUE TITLE
Universal FBP communication protocol

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#19]
Although the name on the link says "Universal", right now "classical" FBP does not talk to it.  Should we discuss how it could be interfaced to "classical" FBP implementations?

@oleksandr and I also started to talk about possible extensions to DrawFBP - does that fit in here?

TIA

**Comment by oleksandr** [comment]
The topic is very ambitious. First would be nice to discuss what kind of communication is required and between which parties. I assume this is related only if there's a runtime/server that accepts graph descriptions in certain format over the network...

**Comment by jonnor** [comment]
@jpaulm: Do you forsee any problems with interfacing with the protocol as defined now?

The protocol basically deals with the notions of
- A set of available components that can be named, enumerated and instantiated
- Manipulating the graph of component instances. adding/removing nodes and edges
- Starting/stopping a network, and optionally introspecting the data flowing along an edge

Nowhere does it not mandate a specific execution strategy in the runtime

**Comment by oleksandr** [comment]
@jonnor does the current NoFlo protocol supports the following scenario:
1. Connect to remote runtime
2. Submit a network for execution
3. Query the status of the network
4. Disconnect
5. Connect to remote runtime
6. List running networks
7. Query/monitor/introspect (to some degree) selected network
8. Terminate selected network

?

**Comment by jonnor** [comment]
For reference, this is the protocol under discussion http://noflojs.org/documentation/protocol

@oleksandr: Yes, all the pieces of that scenario is basically covered already. There are some things which are not widely implemented/tested yet, like running multiple top-level networks. NoFlo UI support for attaching to a running runtime and loading its state is currently in a branch + MicroFlo and imgflo are currently not notifying about graph changes when runtime connect (NoFlo does this right)

**Comment by oleksandr** [comment]
@jonnor Yes, current protocol has some limitations (beside the a bit confusing form of documentation). The key feature for us is running multiple networks on the remote runtime. Besides, the separation between the main and not main graph is also not quite suitable for every case beyond the NoFlo - for instance, the network with subnets can be "flatten" recursively before execution (although submitted as a net with composite components). There're some very NoFlo related things there (set/get source, persist, remote subgraphs - there can be remote components either elementary or composite). The Network subprotocol is very limited. The Graph subprotocol is fine for remote GUIs and design mode, but irrelevant for other cases - when the runtime is execution only system. There were more (I need to check the records tomorrow in the office, as we rejected this work 3 months ago).

Again. It works for the NoFlo and node.js implementations. But that is simply not enough to be called Universal FBP communication protocol.

**Comment by jpaulm** [comment]
Thanks @oleksandr, that was my feeling.   It's a provocative notion, but
right now it should be in a NoFlo-specific section.  I also note that the
link is Universal etc., but the section heading just says Protocol!

Could someone do some restructuring?

BTW it seems more applicable to bottom-up than to top-down design...

Cheers,

Paul

**Comment by jonnor** [comment]
@jpaulm @oleksandr: It also works for MicroFlo (C++ FBP for microcontrollers), imgflo (C dataflow for image processing). rhalff on IRC implemented support for his JavaScript runtime, see https://github.com/psichi/chix-flow.  I also have simple but functional prototypes in Python, as well as for SuperCollider (dataflow environment primarily for audio synthesis), both on my github page.
That is 5 non-NoFlo implementations. How many more is needed to call it universal?

**Comment by jonnor** [comment]
@oleksandr: Have you documented your issues with implementing the protocol anywhere? We're happy to try to address any concrete issues or add things to support usecases we have not come across yet.

**Comment by bergie** [comment]
@jpaulm the fact that none of the "classical" FBP implementations had gotten around to supporting the protocol doesn't say anything of the applicability of the protocol to them. Nothing NoFlo in there except we were the ones to support it. I'd be more than happy to see it implemented for, say, JavaFBP

**Comment by jonnor** [comment]
@oleksandr: 
- The "main"  annotation might need changing to support multiple top-level network. Help appreciated
- set/getsource is optional. And makes sense whenever you want to allow editing the "source code" of the components. For MicroFlo and imgflo I plan to do on-demand compilation of components (written in C/C++).
- persist is also optional. It make sense whenever the runtime itself can store the current graph and automatically load it on restart of the runtime. 
- remote subgraph feature is also optional. It is used to be able to treat an entire top-level network of a runtime as a component for another runtime. This is a feature we have not implemented yet, so we're especially open for changing the protocol in this area.

**Comment by oleksandr** [comment]
@jonnor Those 5 implementations are gathered around NoFlo UI in particular. That was also the reason why we started implementing this protocol as well. The MicroFlo and ImgFlo are the only 2 we can consider serious based on the Github attention. And I assume these 2 are from the same shop :)

The primary reason to drop our work on adopting the protocol work was also the limitation of NoFlo UI (which is off topic here of course): storing graphs in local storage or in github (probably in the future in any git repo) is simply too complex for the end users, who need to learn how to put networks into the repo. The simplest way to read a graph from a local drive and save the modification locally is not there (for obvious reasons).

It was easier to roll out a CLI and a  RESTful API for the runtime to have the job done although we're missing visual editing capabilities. The current NoFlo runtime protocol is describing too much stuff which does not make sense in the scenario I've described above. Too much "optional noise".

Back to the constructive surface :-) I think it makes sense to describe the minimal runtime protocol (not related to UI and graph modification), which is about executing and managing the execution, and call it a Universal FBP protocol for communication with a remote runtime. The rest is too much dependant on your vision of (soon to be done collaborative) editing FBP programs in web-based NoFlo UI.

**Comment by jonnor** [comment]
@oleksandr rhalff implements the protocol it also for his chix-ui IDE. MicroFlo and imgflo two are maintained by the same person (me), so yes, they are hardly independent. :) For the record I had no affiliation with NoFlo/Flowhub when I started the MicroFlo project and implemented the protocol for the first time.

Thing is, we will never have an "universal protocol" if people just go "oh, thats associated with $project-which-first-implemented-it" and then go do their own thing (ad infinitum). That "it does more than I need (right now)" is also not a valid argument, as that is not a disadvantage.[1]

We _have_ described a (proposed) spec for "the minimal runtime protocol (not related to UI and graph modification)". It is found at the link above, just implement with only the capability "protocol:network" and ignore the rest. If this subset needs work for simple usecases, help us fix it?
We should probably restructure our docs to make it possible to see required messages organized by capability...
1. A realistic disadvantage however might be that the transport we've used so far (WebSockets), is peer-to-peer and harder to implement than RESTful HTTP. But thats probably fixable, if the case.

**Comment by oleksandr** [comment]
@jonnor I agree about "universal protocol". Dropping "universal" from the name would make it less confusing. I will document the RESTful protocol from our side so we could compare and proceed with a discussion. From my experience, http://noflojs.org/documentation/protocol/ is hard to comprehend without sniffing the communication between NoFlo UI and the runtime. Although it's based-on on web-sockets some of the messages have a response message, some of them do not. Documenting it in this way with real example message structure would help a lot. After all a protocol is specification of a conversation... a dialog so to say... Please, describe it as a speech-act not as a grammar ;-)

**Comment by trustmaster** [comment]
I've removed the word "Universal" from the TOC so it's less confusing now.

We don't have to go "Ultimate protocol" from the very beginning, the protocol used by NoFlo and others is just good to start with and it's known to work in real world. We can just start with it and improve it gradually, that was the idea when adding a link to it in the wiki.

The documentation it has is indeed hard to grasp, I had the same problem when I started working on a GoFlow runtime. So it's worth recreating the docs in this wiki and fixing the problems detected above along the way:
1. Make the Runtime communication protocol the main and required part of the spec.
2. Put other subprotocols into separate pages and link to them in the TOC at the top of the main page providing clear descriptions on what they are used for.
3. Each protocol message should be documented in the following form:
   - Command
   - Description
   - Request parameters
   - Example request
   - Response properties (if present)
   - Example response (if present)
4. Improve the Runtime protocol using real world experience rather than theoretic possibilities.
5. Split the Transport layer of the protocol into a separate topic and do some work on the transports too.

**Comment by jonnor** [comment]
Agreed on restructuring and doing it in the wiki. Also the "implementations" and "changelog" section should be up front by TOC

**Comment by oleksandr** [comment]
@trustmaster  :+1:

**Comment by jpaulm** [comment]
@trustmaster @oleksandr @jonnor :+1:

**Comment by jonnor** [comment]
Protocol has (finally) moved fron the NoFlo website to
https://github.com/flowbased/fbp-protocol/
