### ISSUE TITLE
flowbased.org domain expired

### ISSUE THREAD

**Issue by samuell** [flowbased/flow-based.org#25]
When visiting flowbased.org, I see this ad site:

![image](https://cloud.githubusercontent.com/assets/125003/15472300/ad4a410a-20fa-11e6-9bb0-dc80f7a07381.png)

**Comment by jpaulm** [comment]
Not sure what happened to flowbased.org domain, but accessing flowbased/flowbased.org on Github of course still works.  Maybe one of us should grab that domain (again?) @trustmaster @bergie @oleksandr

**Comment by trustmaster** [comment]
@samuell thanks for noticing, i'll renew it ASAP.

**Comment by trustmaster** [comment]
Renewed for 2 more years.
