### ISSUE TITLE
0-capacity connections

### ISSUE THREAD

**Issue by trustmaster** [flowbased/flow-based.org#4]
Discussion started by @jpaulm:

> I have never been able to support 0-capacity connections in any of my FBP implementations.  No problem with capacities of 1 and up, but 0 eludes me!  Maybe it's just me, but the DFDM team made a strong effort, and couldn't get it to work!  So theoretically, OK... but pragmatically, in my experience, difficult to impossible!  So, my question: do we leave 0, leave it with qualification, change it to 1, or...?

**Comment by trustmaster** [comment]
The 0-capacity connections in my understanding come from CSP. I guess that you would actually call it a 1-capacity connection instead, but there such connections are considered as 0-capacity. Let me clarify how it works. A sender is always blocked when sending to a zero-capacity connection until the value is actually consumed by a receiver. So it looks like a handshake between a sender and a receiver. Whereas 1-capacity connection allows a sender to start handling the next task right after sending the previous value, but it would block the sender if it is about to send the next value but the receiver hasn't consumed the previous one yet. So it looks like a milkman leaving a bottle of milk at your door and waiting for you to take it before leaving another one.

So, yes, please clarify if we are having the classical "0-based vs. 1-based indexes" issue here or connections are really 1-capacity in classical FBP.

**Comment by jpaulm** [comment]
I think you are saying that connection capacities of 1 and 0 are different, and, if so, I agree.  Connection capacities of > 0 are to me much more FBP-like - as you say, the milkman doesn't have to wait around cooling his heels!  And the larger the connection capacity, the more loosely coupled the producer and the consumer are. 

OTOH a connection capacity of 0 is ultra-tight coupling: I always saw it as two processes basically both having to suspend until both the producer does a send and the consumer does a receive.  In practice, you probably need a shared slot that they can both use, but the slot doesn't act like an FBP connection.  And I have the feeling that this also introduces some additional process states...  So, yes, it could probably be implemented as part of an FBP implementation, but it's a bird of a rather different feather! :-)

**Comment by trustmaster** [comment]
@jpaulm Thanks to you and to Herman, now this is definitely not a matter of what to start indexing with. Which is a good.

As Herman explained, connections behavior is different from implementation to implementation and it's more than just "NoFlo vs. classical".

Back to the original issue of "do we leave 0, leave it with qualification, change it to 1, or...?" my choice is leaving 0 because so it would qualify a wider range of implementations (it doesn't say that an FBP system must have 0-capacity connections available, does it?). And qualifying 0-capacity connection behavior there would be incorrect either, because it depends on concurrency and communication mechanisms used in the implementation. E.g. 0-capacity unbuffered channels work pretty well in Go programs without "ultra-light coupling" because they have lightweight green threads at their service to make processing even more parallel.

**Comment by jpaulm** [comment]
Ahem, I think I wrote "ultra-tight", not "ultra-light"!  

But OK, let's leave it with 0.  One day you can tell me how Go does it!

Regards,

Paul

**Comment by trustmaster** [comment]
@jpaulm, oops, I'm an ultra-fast typo generator, it seems :-)

I can explain how Go does 0-cap today, I just hesitate to hear "this is not FBP" again from you :-)

**Comment by oleksandr** [comment]
:+1:  for 0-cap. My perception of 0-capacity is that a message/IP can never be considered inside of a connection - it's either at the sender's side or at the receiver's port :) Therefore the connection is rather a quantum teleport :-)

**Comment by bergie** [comment]
@oleksandr ...which is the default behavior in NoFlo. Packet gets transmitted immediately to the receiving port, where the port may do buffering if it wants (in which case the _process_ may read from the port at its leisure). There is no particular reason for only limiting to 0-cap connections, as we could easily swap the 0-cap _InternalSocket_ to a N-cap message queue or whatever. But so far this has been enough...

**Comment by oleksandr** [comment]
@bergie Right, the same way the queues are working for other runtimes. I've actually voted to use "0-cap" as notion allowed in FBP. Actually it would be nice to be able to specify a specific arc capacity in the graph definition. But this also brings certain complications :( A question of being really 0-cap depends on the implementation and the hardware of course. Ensuring 0-cap logic could have a lot of communication under the hood in the TPC/IP-networked implementation.

**Comment by alfa256** [comment]
0 capacity is a special case of a bounded buffered connection and it should
be explained as such. Noflo happens to do it due to the constraints of
javascript but building applications in it is architecturally very close to
doing it in a concurrent implementation of FBP, so that's why we consider
it FBP. We talked about this many times and I think that "special case" is
a good enough name. Pointing to the notes about Noflo's buffered ports
would be helpful.

2014-06-13 13:23 GMT-03:00 Oleksandr Lobunets notifications@github.com:

**Comment by bergie** [comment]
@alfa256 not a JavaScript limitation, just a NoFlo implementation detail, and something we could change if we needed to. Some notes on buffered (pull) ports in noflo/noflo#136

**Comment by jpaulm** [comment]
I agree!  Teleportation is a good term!   Definitely a special case!

Paul

**Comment by trustmaster** [comment]
So it should be mentioned on the Concepts page rather than Definition. I'd leave connection capacity characteristics on the Definition page as is for sake of simplicity.

**Comment by jpaulm** [comment]
Added some words to Concepts/Connections about 0-capacity - could @bergie or someone check them?  I guess we can close this issue...?

**Comment by trustmaster** [comment]
@jpaulm, I rephrased it a bit to eliminate "classical vs. NoFlo" in this wiki and make it more general. It also explains that an implementation may have both 0-cap and non-0-cap connections available at the same time.

**Comment by jpaulm** [comment]
Looks great!  So... I will close this issue...
