### ISSUE TITLE
FBP Definition - "dumb data"

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#5]
(Minor issue) "dumb data" - IPs are not totally dumb, as they can have methods in them (at least in the OO language implementations), as e.g. to create "virtual" fields, computed on the fly from other field values.  Could we say that IPs are "passive" objects, whereas processes are "active" - would this help or confuse further?

**Comment by bergie** [comment]
Yeah, technically IPs can be as smart as you want to make them. In NoFlo it is perfectly fine to send for example closures as IPs. But even then they're indeed passive.

**Comment by alfa256** [comment]
The wording is mine, what i mean is that the IPs don't hold anything non
specific to the data itself, that is, sending an instantiated form inside
an IP would not be a smart move. I meant to make a contrast between object
oriented programming that tries to make data as smart as possible, and in
FBP we try to make data as dumb as possible.

2014-06-13 12:03 GMT-03:00 Henri Bergius notifications@github.com:

**Comment by bergie** [comment]
@alfa256 sounds good!

**Comment by jpaulm** [comment]
Just to clarify (as a Github newbie!), _what_ sounds good?!  Alfredo's
note, his original wording, or the latest proposed wording (by me)?

TIA

**Comment by trustmaster** [comment]
I think Alfredo's explanation above sounds good. As for wording, I would pick up Paul's `passive data` instead of `dumb data`.

**Comment by trustmaster** [comment]
@jpaulm great job on the update! I'm closing the issue.
