### ISSUE TITLE
FBP Definition - "processes" or "components"

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#6]
While writing the previous issue, I noticed that the definition talks about "components" as nodes, etc.  Actually, in my book I distinguish between "components" - the code itself - and "processes" - instances of components in the network.  we need to stress that you can have multiple instances of a component in the same network.

That said, I realize that "process" is an ambiguous term in programming.  In my book, 2nd ed., page ix. (Preface to 2nd ed.), I found a whole bunch of terms used in the literature for "unit of concurrency" - all no doubt with their own connotations:

process (Erlang)
actor (actor theory)
agent
transaction
thread
operator (MIT, Expressor, et al.)
vat (E language)
island (Tweak)
task (Ada)
resource (Minuet)
stage (John Hartmann’s CMS Pipelines)

I don't know what the derivation of "vat" is - something you brew beer in?

Any preferences?!

**Comment by bergie** [comment]
Here is how I've been using the terms in NoFlo, essentially distinguishing "definitions" from actual live instances.

Not live:
- **component** - definition (usually a class) for a process that can be instantiated
- **graph** - definition for a network consisting of nodes, edges, and IIPs (as well as other metadata like groups)
- **node** - node in a graph that is not yet live
- **edge** - edge in a graph connecting ports of different nodes

Live:
- **network** - a running instance of a graph, consisting of _processes_ and _connections_
- **process** - node in a running network, essentially an instantiated _component_ based on what was defined in the _node_
- **connection** - live connection between process ports in a network based on an _edge_ definition

**Comment by jpaulm** [comment]
I am comfortable with that terminology!  So IMO the Definition and
Characteristics need to have most of the uses of "component" changed to
"process".  Volunteers?!

Paul

**Comment by oleksandr** [comment]
:+1: I like the terminology.

**Comment by jpaulm** [comment]
Seems as though "process" has been accepted - I didn't hear any loud outcry against it!  So I have updated the Definition page, and I think we can close this one...
