### ISSUE TITLE
FBP Process Activation 

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#7]
Currently in the Characteristics section it says: 

> Activation: From the graph designer point of view all processes are running all the time, and the library should handle activations accordingly to maintain this illusion. 

This is generally true, and much of the job of the software is to "maintain this illusion", but I guess I wouldn't stress "all the time" quite so much! There may be pragmatic reasons why you don't want one or more processes to start immediately at application start.  Here are a couple:
- a common trick in batch "classical" FBP is to write a stream of IPs to a file, and then read it back.  This acts as a very large buffer, and is often used to resolved certain types of deadlock.  For historical reasons, it is often referred to as an "infinite queue".  Clearly the Reader should not start until the Writer has closed the file.  While you can have the Reader start earlier, the file it is working on must not be opened too early!
- although there would be no overhead to waiting for work if all processes had their own processors, in practice you probably don't want to start paying overhead until you actually need a function.  In some applications, we found that 2/3 of the processes in a given network had to do with error handling, so might never actually get sent any data to work on!

Could we say something like: 

> Activation: From the graph designer point of view processes are running concurrently, and it is the function of the scheduling software to allocate CPU time and manage other services as required to maintain this illusion.

**Comment by bergie** [comment]
@jpaulm agreed. For an addition, how do you like the following from [NoFlo component lifecycle docs](http://noflojs.org/documentation/components/#lifecycle):

> Before a process has received data it should be _inert_, merely listening to its input ports. Processes that need to start doing something when a network is started should be triggered to do so by sending them an Initial Information Packet.

The basic point here is that a process shouldn't start doing something just by the virtue of having been instantiated into the network. There should be something coming to it from upstream before it acts / the scheduler wakes it up.

**Comment by trustmaster** [comment]
I agree with @jpaulm 's correction. And it is brief enough for the characteristics list. I wouldn't bother the reader by introducing all possible states of a process in that list.

**Comment by jpaulm** [comment]
Good - as long as we point out that this is specific to NoFlo.

In FBP, you can't _send_ an IIP.  If IPs are "passive", IIPs are
super-passive - they don't have any effect on processing at all until the
component does a "receive" on the port they are attached to, at which point
the IIP is converted to a regular IP - subject to all the rules affecting
regular IPs.

Also, FBP processes don't have an "inert" state, although I like the term!
They are either "not started", "suspended", "active", or "dormant".
Once they are started, of course they can listen to their heart's content!

The difference probably reflects the fact that IIUC a NoFlo component
doesn't do anything (except listen) until one of the callbacks is triggered.

So I'll defer to the wordsmiths on this one!

Cheers,

Paul

**Comment by jpaulm** [comment]
That raises another interesting question.  There is currently no mention of IIPs in the Definition or Characteristics (that I could see).  Probably a good thing right now, given the differing views of IIPs!

Can anyone come up with a general statement that covers all the variations?

**Comment by trustmaster** [comment]
@jpaulm, it's in the [Concepts](https://github.com/flowbased/flowbased.org/wiki/Concepts#initial-information-packets). Characteristics don't have to cover everything, it covers most important differences from other Dataflow systems.

**Comment by oleksandr** [comment]
Here we slightly touch the topic I’ve mentioned yesterday: the lifecycle of a process depends on the specific implementation of the FBP runtime. 
In cases where the scheduler is responsible of taking an IP from the output port of one process and feeding it into an input port of another process it is possible to have the real “not started” and “suspended states. But in the implementations where processes are connected via a certain communication middleware directly (socket-to-socket or goroutine-to-goroutine) these states are rather faked/conceptual because the scheduler is less involved. How would this impact the classification of an implementation - FBP or any other flavour of DataFlow?

Best,
Alex

**Comment by oleksandr** [comment]
Is there any summary of the conflicting opinions on IIP? To me it’s just an IP, which is send by a scheduler/runtime (not a component) once at the end of the bootstrap of the network.

Alex.

**Comment by bergie** [comment]
@oleksandr yeah, that is how they work in NoFlo. The network "sends" them when it starts, at which point they become IPs just like any else, except that they don't have a "from address"

**Comment by oleksandr** [comment]
Where should we include information of "deactivation" (network shutdown) patterns? I've just faced this in our implementation and looking into proper ways to have a graceful network shutdown. I recall from the book that monitoring of the input ports can trigger the cascade effect of shutting down the processes (input disconnected, close output port, shutdown process; the downstream detects input disconnected and so on). What about other exceptional cases when a process closes down its input port and shutdown is propagated upstream direction?

**Comment by trustmaster** [comment]
I think the basic shutdown rule (upstream processes close their outputs causing downstream processes to close their outputs and shut down and so on) should go to the Concepts, and advanced shutdown methods like dowstream-up and immediate termination of all processes should go to Advanced features page because they are implementation-specific.

**Comment by alfa256** [comment]
I think that shutdown is always implementation specific, from the
architectural view the network is always running so we should explain that
a process finishes whenever it wants to, and reactivated as needed.

2014-06-14 15:01 GMT-03:00 Vladimir Sibirov notifications@github.com:

**Comment by jpaulm** [comment]
I wrote earlier:

> That raises another interesting question. There is currently no mention of IIPs in the Definition or Characteristics (that I could see).

@trustmaster says it is in Concepts, but I would like to see a general statement about IIPs in Characteristics.  I have taken a stab at it - feedback/modification would be welcome!

**Comment by trustmaster** [comment]
@jpaulm, thanks for adding! It is good as is, or considering that characteristics is a just a bulleted list with brief statements, I'd rather make it shorter and introduced the IIP term in it.

**Comment by jpaulm** [comment]
Sorry @trustmaster , I am not clear what you are suggesting...!  I'm happy to have my addition be shorter - maybe you can suggest some wording...?  I just thought IIPs needed to be mentioned in the context of componentry.

**Comment by trustmaster** [comment]
@jpaulm, I've just recombined your phrases to make it a bit shorter and added the mention of "IIP" itself there. Please have a look!

**Comment by jpaulm** [comment]
Yes, I think that's fine!    I thought it was good to provide a sort of
heads-up to expect varying implementations!

Thanks for the improved wording!

Regards,

Paul

On Sun, Jun 15, 2014 at 11:30 AM, Vladimir Sibirov <notifications@github.com
