### ISSUE TITLE
Ports (in Concepts)

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#8]
> A Process can send and recieve from any of the ports but should restrict itself to only a read or write operation at the same time.

Huh?  Are you saying that a process is single-threaded, and can only wait on one event at a time, e.g. receive, send, wait on event, wait for time, etc. (as we have said elsewhere, I think...)?  Or are you trying to include some NoFlo ideas as well?  TIA

**Comment by alfa256** [comment]
I'm trying to say that a process should have only a thread ( if it owns
several ) that does the reading and writing to avoid a the problem we are
trying to solve with FBP.

2014-06-17 22:52 GMT-03:00 jpaulm notifications@github.com:

**Comment by oleksandr** [comment]
This is up to a component. Don't break a black box model based on a particular implementation and put such requirements.

**Comment by jpaulm** [comment]
Allowing one process to have more than one thread seems to me to go against
the philosophy of FBP - it means that the person coding it has to worry
about locks, etc., which FBP normally spares him/her from...  I actually do
that in the (experimental) Balloon component of JavaFBP, but this is
definitely not "normal" FBP coding!

**Comment by bergie** [comment]
I agree with @oleksandr on this one. Components should be black boxes, and we should only care about what happens on the port boundary.

For example, we have bunch of components that talk to external web services. Who knows how many "threads" a Facebook API call ends up spawning? And yet from NoFlo perspective all of that happens inside a single component instance (process) ;-)

**Comment by alfa256** [comment]
My point is that you can't restrict a component from having its own thread
pool, there's no way to do that, so it's just a suggestion. A friend wanted
to use many threads to listen to several ports and that was a bad design,
that is the motivation for the comment. They are black boxes but I want to
discourage such complexity.
I'll change the wording to something better.

2014-06-18 10:27 GMT-03:00 Henri Bergius notifications@github.com:

**Comment by jpaulm** [comment]
I agree, and @bergie I find it interesting that this is also true for my
JavaFBP WebsocketReceive component - there are multiple webworkers doing
their thing, but the FBP network just sees a single stream of requests
coming out of one process...

**Comment by oleksandr** [comment]
@jpaulm The multithreaded component can be written in a language that discourage usage of conventional sync primitives (mutex/lock/semaphore/etc). As @bergie pointed out some of the libraries a component would rely on could spawn own threads. 

After all the pragmatism behind a requirement of a single thread per component is to simplify developer's life. I would mentioned this as a recommendation, not a strict requirement. As an example, in Go developers are encouraged to use goroutines and channels for concurrent programming, but they can still share memory with mutex/locks and make their life difficult :)

**Comment by jpaulm** [comment]
@alfa256 (and everyone) - good discussion!  Curious to see how you reword the section I found confusing - I confess I still find it so, even after this discussion!

**Comment by jpaulm** [comment]
@alfa256 @oleksandr @bergie Could someone reword the sentence in question?  I really feel it's not clear.   Here it is again:

> A Process can send and receive from any of the ports but should restrict itself to only a read or write operation at the same time.

TIA

**Comment by oleksandr** [comment]
I can only suggest to remove this sentence.

**Comment by jpaulm** [comment]
Yes, I agree.  However, I never know who should make changes...  How about
if I do it?  Unless @alfa256, you want to try for a rephrasing...?

**Comment by jpaulm** [comment]
Thanks @alfa256 !  That looks great!  I have just done a bit of grammar and punctuation tweaking!
